### ISSUE TITLE
Doesn't seem to work

### ISSUE THREAD

**Issue by pawndev** [ScreepsMods/screepsmod-pure-automation#3]
Hello!

I tried to put this mod on my server (launched via screeps-laucher). I referenced it in config.yml, and is correctly in mods.json.
But, I can continue to "suicide" my creeps.

How can I test if the mod is correctly loaded ? 

Thanks in advance

**Comment by AlinaNova21** [comment]
Check in `logs/backend.log`, it should list the mods when the server starts, make sure theres no error there, if you are using other mods like screepsmod-mongo, may also need to make sure this mod is first so it inserts its routes before them.

**Comment by pawndev** [comment]
Thanks for your reply, it was helpful!
The mod was correctly loaded, the only point is about order loading, I put this mod in first (before mongo) and it seems to work correctly.
I will continue my test and will tell you if it's okey!

Thanks again!

**Comment by pawndev** [comment]
Maybe we could wrote this information in the readme of this repository ?
Oh, also, now my plugin is correctly loaded, do you know how I can put my very first spawn ?

**Comment by AlinaNova21** [comment]
You would either need to add an entry in `.screepsrc` (It hasn't been updated with config.yml support) or do like botarena and enable the mod after spawning.
```ini
[pureAutomation]
placeSpawn = true
```

**Comment by AlinaNova21** [comment]
You can also enable and disable the mod in CLI with `pureAutomation.enable()` and `pureAutomation.disable()` (It will always be enabled by default on server start)

**Comment by pawndev** [comment]
Okey, thanks for your help! 😄
